# Generated by Django 5.0.6 on 2024-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_movies', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
